[package]
name = "solana-token-project"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.10.32"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"